//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.22 at 12:53:16 PM GMT 
//


package net.b2net.utils.iot.server.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.b2net.utils.iot.server.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.b2net.utils.iot.server.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IoTConfiguration.StreamingProvider }
     * 
     */
    public IoTConfiguration.StreamingProvider createIoTConfigurationStreamingProvider() {
        return new IoTConfiguration.StreamingProvider();
    }

    /**
     * Create an instance of {@link IoTConfiguration }
     * 
     */
    public IoTConfiguration createIoTConfiguration() {
        return new IoTConfiguration();
    }

    /**
     * Create an instance of {@link IoTConfiguration.JsonServer }
     * 
     */
    public IoTConfiguration.JsonServer createIoTConfigurationJsonServer() {
        return new IoTConfiguration.JsonServer();
    }

    /**
     * Create an instance of {@link IoTConfiguration.Server }
     * 
     */
    public IoTConfiguration.Server createIoTConfigurationServer() {
        return new IoTConfiguration.Server();
    }

    /**
     * Create an instance of {@link IoTConfiguration.DatabaseProvider }
     * 
     */
    public IoTConfiguration.DatabaseProvider createIoTConfigurationDatabaseProvider() {
        return new IoTConfiguration.DatabaseProvider();
    }

}
